### ISSUE TITLE
hunspell integration?

### ISSUE THREAD

**Issue by duydo** [phamquick/elastic-hunspell-dictionary#1]
Hi em @phamquick, 

Elasticsearch đã tích hợp sẵn hunspell, em định làm gì với plugin này vậy?

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-hunspell-tokenfilter.html

**Comment by phamquick** [comment]
Em chào anh @duydo 
Em muốn bỏ dấu tiếng Việt ạ. Em có đọc qua một bài viết họ sử dụng hunspell để loại bỏ dấu, em cũng tìm được bộ dictionary tiếng Việt cho hunspell để thử loại bỏ dấu nhưng không thành ạ.
Em cũng đã mò ra được giải pháp bỏ dấu để hỗ trợ tìm kiếm tiếng Việt không dấu rồi ạ. Đó là dùng filter "asciifolding" có sẵn trong Elasticsearch.

Anh ơi còn một vấn đề nữa em muốn hỏi anh mong anh trả lời giúp em ạ. Em đã thử sử dụng filter "lowercase" để bỏ chữ viết hoa rồi, mà tại sao khi em phân tích "công nghệ thông tin việt nam" nó lại thành:  "công nghệ thông tin", "việt" , "nam" ạ? nhưng khi viết thành "Việt Nam" thì nó lại phân tích đúng ạ.

Em đã setting giống như dưới ạ:

{
  "settings" : {
    "analysis":{
      "analyzer" :{
        "vi" :{
          "type": "custom",
          "tokenizer": "vi_tokenizer",
          "filter" : ["lowercase","asciifolding"]
        }
      }
    }
  }
}

Rất mong nhận được câu trả lời của anh. Trân thành cảm ơn anh^^!

**Comment by phamquick** [comment]
cái Repository này em up lên là chỉ để lưu trữ thôi ạ. cũng không có gì đâu ạ^^!

**Comment by duydo** [comment]
Em phải tokenizer trước khi apply lowercase filter vì Việt Nam là tên địa danh, cần viết chính xác thì bộ tách từ mới hoạt động được. Khi em viết thường "việt nam" nó xem là 2 từ bình thường nên tách ra làm 2.
